In [2]:
import torch

In [7]:
a = torch.tensor(list(range(2*2*3))).view(2,2,3)

In [8]:
a

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])

In [9]:
a.shape

torch.Size([2, 2, 3])

In [11]:
indices = torch.tensor([[[1,0,0],[0,1,0]],[[0,1,0],[0,0,1]]])

In [12]:
indices

tensor([[[1, 0, 0],
         [0, 1, 0]],

        [[0, 1, 0],
         [0, 0, 1]]])

In [13]:
indices.shape

torch.Size([2, 2, 3])

In [14]:
torch.bmm(a, indices.permute(0,2,1))

tensor([[[ 0,  1],
         [ 3,  4]],

        [[ 7,  8],
         [10, 11]]])